### PR TITLE
Waiting until Internet Explorer process being debugged has exited before continuing when using the web server

### LINKED ISSUE #787: When using Server Mode debug in Test Explorer does not work
# Summary
Debugging from the Test Explorer with Server mode turned on almost always fails. It looks like the test harness is completing and the web server (setup by Chutzpah) is being closed BEFORE Visual Studio has time to get in and launch and connect to a browser.

Running debug from the Context Menu "Run Chutzpah with Debugger" works just fine in the exact same code base and configuration.

I'm guessing this is about how the lifecycle of the Web Server is controlled but I would naturally expect the two ways of debugging to work in the same way (and the following would appear to agree: https://github.com/mmanela/chutzpah/wiki/Debugging-Unit-Tests).

# Details
Basic steps in any VS solution where Server Mode is enabled (explicitly or implicitly through the use of Chrome of JsDom engines):

Repo: https://github.com/john-swallow-cenduit/ChutzpahDebugIssue

- Build the solution so that Chutzpah picks up the single test.
- Put a breakpoint in the test.
- Locate the test in test explorer. 
- Run Debug and wait.

Expected: Browser starts. Jasmine page is loaded. Breakpoint is hit.
Actual: Most of the time it will launch an IE window and throw up a "Cannot reach this page" error.

Full details of all versions used are in the readme.md of the repo but the Chutzpah versions in use:
- Chutzpah 4.4.10
- Chutzpah Context Menu 4.4.9
- Chutzpah Test Adapter for Visual Studio 2012 4.4.9

I've included a bunch more observations in the readme.md in the repo but I have attempted to draw out just the pertinent ones here for the sake of brevity.

### PR DESCRIPTION
**Pull request by icnocop**
Added IEBrowserTabOpenTimeout setting
Fixed typos
Waiting until Internet Explorer process being debugged has exited before continuing when using the web server
Using Microsoft.VisualStudio.Shell.14 nuget package
Using Microsoft.VSSDK.BuildTools.15.0.26201 released nuget package
Fixes #787

### CODE REVIEW

File: Chutzpah/Models/ChutzpahTestSettingsFile.cs [hunk 1]
```diff
@@ -396,6 +396,8 @@ public Regex TestPatternRegex
             }
         }
 
+        public int? IEBrowserTabOpenTimeout { get;  set; }
```
Comment (mmanela) [inline Chutzpah/Models/ChutzpahTestSettingsFile.cs:399]: Does this need to be a setting? I am fine with it but curious when someone would need to adjust.

**Comment by mmanela** [comment]
This is a great PR. Some questions/comments

1. Wow, thanks for the typo fixes. That is quite embarrassing ;) 
2. What versions of VS did you test this on?  (Do you know if the upgrades / additions on the nuget packages will affect version compatibility?)

File: Chutzpah/Models/ChutzpahTestSettingsFile.cs (hunk 1 above)
Comment (icnocop) [reply Chutzpah/Models/ChutzpahTestSettingsFile.cs:399]: When I was first encountering this issue, I thought maybe the Chutzpah Test Adapter wasn't able to find the IE tab within the default 4 second timeout because I thought IE may have still been trying to load.

I could imagine this would be an issue on relatively slow machines, when other processes are fighting for resources, or if there are any IE add-ons that take some time to load with the browser.

It also seems like having a hard-coded timeout value isn't the best practice.

I can revert this change if you think it's best.

Thank you.

Comment (mmanela) [reply Chutzpah/Models/ChutzpahTestSettingsFile.cs:399]: Oh I am fine with it, just wanted to understand the rationale.

**Comment by icnocop** [comment]
Thank you for the code review.

>     1. Wow, thanks for the typo fixes. That is quite embarrassing ;)

No worries. :)

>     2. What versions of VS did you test this on?  (Do you know if the upgrades / additions on the nuget packages will affect version compatibility?)

I built the code using Visual Studio 2017 and tested on Visual Studio 2019.

I don't think the upgrades should affect version compatibility because I kept the same major version.

Can the sample projects be open in older versions of Visual Studio and be used to test backwards compatibility?

**Comment by icnocop** [comment]
Here is Chutzpah.VS2012.vsix built from this pull request, installing on another machine with Visual Studio 2015, 2017, and 2019 installed:

image

image

**Comment by icnocop** [comment]
Here is the Test Explorer window in Visual Studio 2015:

image

**Comment by icnocop** [comment]
Let me know if you'd like me to squash my commits into one.

**Comment by mmanela** [comment]
Its fine, sorry for the delay. I didn't have a window environment setup, just got a VM built and will take a look.

**Comment by mmanela** [comment]
Ok works! Thanks for the great PR
